name: Modula Final Tiles Migrator deploy
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Modula Final Tiles Migrator
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: modula-final-tiles-migrator
